<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/06/13 14:29:22
sfConfig::add(array(
  'mod_discussionsstatus_enabled' => true,
  'mod_discussionsstatus_view_class' => 'sfPHP',
));
