<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/06/13 04:44:40
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'allow_manage_users',
  ),
);
