<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/06/13 14:32:51
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
